language: cpp
dist: bionic
compiler: gcc

env:
  matrix:
    - TARGET=desktop
    - TARGET=rpi

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-venv
      - gcc-8
      - g++-8
      - g++-8-arm-linux-gnueabi
      - g++-8-arm-linux-gnueabihf
      - gcc-8-arm-linux-gnueabi
      - gcc-8-arm-linux-gnueabihf

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90
# Install conan
  - python3 -m pip install --user virtualenv
  - python3 -m venv conan
  - source conan/bin/activate
  - pip install conan
# Automatic detection of your arch, compiler, etc.
  - conan user
# Add conan remote repositories, clone rpi compiler
  - ./setup-environment.sh

script:
  - if [ $TARGET == "desktop" ]; then
    ./build.sh;
    elif [ $TARGET == "rpi" ]; then
    ./build-rpi.sh;
    fi
  - if [ $TARGET == "desktop" ]; then
    cd build && make test;
    fi
