language: cpp
dist: xenial
compiler: gcc

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-venv

jobs:
  include:
    - stage: RPI
      install:
# Install conan
        - python3 -m pip install --user virtualenv
        - python3 -m venv conan
        - source conan/bin/activate
        - pip install conan
# Automatic detection of your arch, compiler, etc.
        - conan user
# Add conan remote repositories, clone rpi compiler
        - ./setup-environment.sh
        - git clone https://github.com/raspberrypi/tools.git
# Install conan dependencies, cmake and make
        - mkdir build && cd build
        - conan install .. --build=missing --profile ../rpi_profile
        - cmake .. -DCMAKE_TOOLCHAIN_FILE=../Toolchain-RaspberryPi.cmake -DCMAKE_BUILD_TYPE=Release

      script:
        - make -j$(nproc)
    - stage: linux
      install:
# Install conan
        - python3 -m pip install --user virtualenv
        - python3 -m venv conan
        - source conan/bin/activate
        - pip install conan
# Automatic detection of your arch, compiler, etc.
        - conan user
# Add conan remote repositories, clone rpi compiler
        - ./setup-environment.sh
# Install conan dependencies, cmake and make
        - mkdir build && cd build
        - conan install .. --build=missing
        - cmake .. -DCMAKE_BUILD_TYPE=Release

      script:
        - make -j$(nproc)
        - make test
