language: cpp
dist: disco
compiler: gcc

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-venv
      - gcc-8
      - g++-8
      - g++-8-arm-linux-gnueabi
      - g++-8-arm-linux-gnueabihf
      - gcc-8-arm-linux-gnueabi
      - gcc-8-arm-linux-gnueabihf
      - libprotoc-dev
      - protobuf-compiler-grpc

jobs:
  include:
    - stage: linux
      install:
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90
# Install conan
        - python3 -m pip install --user virtualenv
        - python3 -m venv conan
        - source conan/bin/activate
        - pip install conan
# Automatic detection of your arch, compiler, etc.
        - conan user
# Add conan remote repositories, clone rpi compiler
        - ./setup-environment.sh
# Install conan dependencies, cmake and make
        - mkdir build && cd build
        - conan install .. --build=missing
        - cmake .. -DCMAKE_BUILD_TYPE=Release

      script:
        - make -j$(nproc)
        - make test
    - stage: RPI
      install:
# Install conan
        - python3 -m pip install --user virtualenv
        - python3 -m venv conan
        - source conan/bin/activate
        - pip install wheel
        - pip install conan
# Automatic detection of your arch, compiler, etc.
        - conan user
# Add conan remote repositories, clone rpi compiler
        - ./setup-environment.sh
# Install conan dependencies, cmake and make
        - mkdir build && cd build
        - conan install .. --build=missing --profile ../rpi_profile
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../Toolchain-RaspberryPi.cmake

      script:
        - make -j$(nproc)
