language: cpp
dist: xenial
compiler: gcc

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-venv

install:
# Install conan
  - python3 -m pip install --user virtualenv
  - python3 -m venv conan
  - source conan/bin/activate
  - pip install conan
# Automatic detection of your arch, compiler, etc.
  - conan user
# Add conan remote repositories, clone rpi compiler
  - ./setup-environment.sh
# Install conan dependencies, cmake and make
  - mkdir build && cd build
  - conan install .. --build=missing --profile ../rpi_profile
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=../Toolchain-RaspberryPi.cmake 

script:
  - make -j$(nproc)
